/**
 * @fileoverview gRPC-Web generated client stub for towns
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.6.1
// source: user_generator.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.towns = require('./user_generator_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.UserGeneratorServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.UserGeneratorServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.towns.GenerateUserRequest,
 *   !proto.towns.GenerateUserResponse>}
 */
const methodDescriptor_UserGeneratorService_GenerateUser = new grpc.web.MethodDescriptor(
  '/towns.UserGeneratorService/GenerateUser',
  grpc.web.MethodType.UNARY,
  proto.towns.GenerateUserRequest,
  proto.towns.GenerateUserResponse,
  /**
   * @param {!proto.towns.GenerateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.towns.GenerateUserResponse.deserializeBinary
);


/**
 * @param {!proto.towns.GenerateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.towns.GenerateUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.towns.GenerateUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.towns.UserGeneratorServiceClient.prototype.generateUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/towns.UserGeneratorService/GenerateUser',
      request,
      metadata || {},
      methodDescriptor_UserGeneratorService_GenerateUser,
      callback);
};


/**
 * @param {!proto.towns.GenerateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.towns.GenerateUserResponse>}
 *     Promise that resolves to the response
 */
proto.towns.UserGeneratorServicePromiseClient.prototype.generateUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/towns.UserGeneratorService/GenerateUser',
      request,
      metadata || {},
      methodDescriptor_UserGeneratorService_GenerateUser);
};


module.exports = proto.towns;

