/**
 * @fileoverview gRPC-Web generated client stub for towns
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.12.4
// source: room_list_provider.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.towns = require('./room_list_provider_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.RoomListProviderServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.RoomListProviderServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.towns.GetRoomListRequest,
 *   !proto.towns.GetRoomListResponse>}
 */
const methodDescriptor_RoomListProviderService_GetRoomList = new grpc.web.MethodDescriptor(
  '/towns.RoomListProviderService/GetRoomList',
  grpc.web.MethodType.UNARY,
  proto.towns.GetRoomListRequest,
  proto.towns.GetRoomListResponse,
  /**
   * @param {!proto.towns.GetRoomListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.towns.GetRoomListResponse.deserializeBinary
);


/**
 * @param {!proto.towns.GetRoomListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.towns.GetRoomListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.towns.GetRoomListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.towns.RoomListProviderServiceClient.prototype.getRoomList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/towns.RoomListProviderService/GetRoomList',
      request,
      metadata || {},
      methodDescriptor_RoomListProviderService_GetRoomList,
      callback);
};


/**
 * @param {!proto.towns.GetRoomListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.towns.GetRoomListResponse>}
 *     Promise that resolves to the response
 */
proto.towns.RoomListProviderServicePromiseClient.prototype.getRoomList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/towns.RoomListProviderService/GetRoomList',
      request,
      metadata || {},
      methodDescriptor_RoomListProviderService_GetRoomList);
};


module.exports = proto.towns;

