/**
 * @fileoverview gRPC-Web generated client stub for towns
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: proto/user_name_provider.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

const proto = {};
proto.towns = require("./user_name_provider_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.UserNameProviderServiceClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.UserNameProviderServicePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.towns.GetNameRequest,
 *   !proto.towns.GetNameResponse>}
 */
const methodDescriptor_UserNameProviderService_GetName =
  new grpc.web.MethodDescriptor(
    "/towns.UserNameProviderService/GetName",
    grpc.web.MethodType.UNARY,
    proto.towns.GetNameRequest,
    proto.towns.GetNameResponse,
    /**
     * @param {!proto.towns.GetNameRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.towns.GetNameResponse.deserializeBinary
  );

/**
 * @param {!proto.towns.GetNameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.towns.GetNameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.towns.GetNameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.towns.UserNameProviderServiceClient.prototype.getName = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/towns.UserNameProviderService/GetName",
    request,
    metadata || {},
    methodDescriptor_UserNameProviderService_GetName,
    callback
  );
};

/**
 * @param {!proto.towns.GetNameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.towns.GetNameResponse>}
 *     Promise that resolves to the response
 */
proto.towns.UserNameProviderServicePromiseClient.prototype.getName = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/towns.UserNameProviderService/GetName",
    request,
    metadata || {},
    methodDescriptor_UserNameProviderService_GetName
  );
};

module.exports = proto.towns;
