/**
 * @fileoverview gRPC-Web generated client stub for towns
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: proto/city_updater.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

const proto = {};
proto.towns = require("./city_updater_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.CityUpdaterServiceClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.CityUpdaterServicePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.towns.UpdateCityRequest,
 *   !proto.towns.UpdateCityResponse>}
 */
const methodDescriptor_CityUpdaterService_UpdateCity =
  new grpc.web.MethodDescriptor(
    "/towns.CityUpdaterService/UpdateCity",
    grpc.web.MethodType.UNARY,
    proto.towns.UpdateCityRequest,
    proto.towns.UpdateCityResponse,
    /**
     * @param {!proto.towns.UpdateCityRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.towns.UpdateCityResponse.deserializeBinary
  );

/**
 * @param {!proto.towns.UpdateCityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.towns.UpdateCityResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.towns.UpdateCityResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.towns.CityUpdaterServiceClient.prototype.updateCity = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/towns.CityUpdaterService/UpdateCity",
    request,
    metadata || {},
    methodDescriptor_CityUpdaterService_UpdateCity,
    callback
  );
};

/**
 * @param {!proto.towns.UpdateCityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.towns.UpdateCityResponse>}
 *     Promise that resolves to the response
 */
proto.towns.CityUpdaterServicePromiseClient.prototype.updateCity = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/towns.CityUpdaterService/UpdateCity",
    request,
    metadata || {},
    methodDescriptor_CityUpdaterService_UpdateCity
  );
};

module.exports = proto.towns;
