/**
 * @fileoverview gRPC-Web generated client stub for towns
 * @enhanceable
 * @public
 */
/* eslint-disable */
// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: proto/random_joiner.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

const proto = {};
proto.towns = require("./random_joiner_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.RandomRoomJoinerServiceClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.RandomRoomJoinerServicePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.towns.JoinRandomRoomRequest,
 *   !proto.towns.JoinRandomRoomResponse>}
 */
const methodDescriptor_RandomRoomJoinerService_JoinRandomRoom =
  new grpc.web.MethodDescriptor(
    "/towns.RandomRoomJoinerService/JoinRandomRoom",
    grpc.web.MethodType.UNARY,
    proto.towns.JoinRandomRoomRequest,
    proto.towns.JoinRandomRoomResponse,
    /**
     * @param {!proto.towns.JoinRandomRoomRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.towns.JoinRandomRoomResponse.deserializeBinary
  );

/**
 * @param {!proto.towns.JoinRandomRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.towns.JoinRandomRoomResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.towns.JoinRandomRoomResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.towns.RandomRoomJoinerServiceClient.prototype.joinRandomRoom = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/towns.RandomRoomJoinerService/JoinRandomRoom",
    request,
    metadata || {},
    methodDescriptor_RandomRoomJoinerService_JoinRandomRoom,
    callback
  );
};

/**
 * @param {!proto.towns.JoinRandomRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.towns.JoinRandomRoomResponse>}
 *     Promise that resolves to the response
 */
proto.towns.RandomRoomJoinerServicePromiseClient.prototype.joinRandomRoom =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/towns.RandomRoomJoinerService/JoinRandomRoom",
      request,
      metadata || {},
      methodDescriptor_RandomRoomJoinerService_JoinRandomRoom
    );
  };

module.exports = proto.towns;
