/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
var jspb = require("google-protobuf");
var goog = jspb;
var global = Function("return this")();

goog.exportSymbol("proto.towns.JoinResponseStatus", null, global);
goog.exportSymbol("proto.towns.JoinRoomRequest", null, global);
goog.exportSymbol("proto.towns.JoinRoomResponse", null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.towns.JoinRoomRequest = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    null,
    proto.towns.JoinRoomRequest.oneofGroups_
  );
};
goog.inherits(proto.towns.JoinRoomRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.towns.JoinRoomRequest.displayName = "proto.towns.JoinRoomRequest";
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.towns.JoinRoomRequest.oneofGroups_ = [[1], [2]];

/**
 * @enum {number}
 */
proto.towns.JoinRoomRequest.AuthTokenCheckerCase = {
  AUTH_TOKEN_CHECKER_NOT_SET: 0,
  AUTH_TOKEN: 1,
};

/**
 * @return {proto.towns.JoinRoomRequest.AuthTokenCheckerCase}
 */
proto.towns.JoinRoomRequest.prototype.getAuthTokenCheckerCase = function () {
  return /** @type {proto.towns.JoinRoomRequest.AuthTokenCheckerCase} */ (
    jspb.Message.computeOneofCase(
      this,
      proto.towns.JoinRoomRequest.oneofGroups_[0]
    )
  );
};

/**
 * @enum {number}
 */
proto.towns.JoinRoomRequest.RoomIdCheckerCase = {
  ROOM_ID_CHECKER_NOT_SET: 0,
  ROOM_ID: 2,
};

/**
 * @return {proto.towns.JoinRoomRequest.RoomIdCheckerCase}
 */
proto.towns.JoinRoomRequest.prototype.getRoomIdCheckerCase = function () {
  return /** @type {proto.towns.JoinRoomRequest.RoomIdCheckerCase} */ (
    jspb.Message.computeOneofCase(
      this,
      proto.towns.JoinRoomRequest.oneofGroups_[1]
    )
  );
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.towns.JoinRoomRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.towns.JoinRoomRequest.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.towns.JoinRoomRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.towns.JoinRoomRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        authToken: jspb.Message.getFieldWithDefault(msg, 1, ""),
        roomId: jspb.Message.getFieldWithDefault(msg, 2, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.towns.JoinRoomRequest}
 */
proto.towns.JoinRoomRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.towns.JoinRoomRequest();
  return proto.towns.JoinRoomRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.towns.JoinRoomRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.towns.JoinRoomRequest}
 */
proto.towns.JoinRoomRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setAuthToken(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setRoomId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.towns.JoinRoomRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.towns.JoinRoomRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.towns.JoinRoomRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.towns.JoinRoomRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(1, f);
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(2, f);
  }
};

/**
 * optional string auth_token = 1;
 * @return {string}
 */
proto.towns.JoinRoomRequest.prototype.getAuthToken = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/** @param {string} value */
proto.towns.JoinRoomRequest.prototype.setAuthToken = function (value) {
  jspb.Message.setOneofField(
    this,
    1,
    proto.towns.JoinRoomRequest.oneofGroups_[0],
    value
  );
};

proto.towns.JoinRoomRequest.prototype.clearAuthToken = function () {
  jspb.Message.setOneofField(
    this,
    1,
    proto.towns.JoinRoomRequest.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.towns.JoinRoomRequest.prototype.hasAuthToken = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional string room_id = 2;
 * @return {string}
 */
proto.towns.JoinRoomRequest.prototype.getRoomId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/** @param {string} value */
proto.towns.JoinRoomRequest.prototype.setRoomId = function (value) {
  jspb.Message.setOneofField(
    this,
    2,
    proto.towns.JoinRoomRequest.oneofGroups_[1],
    value
  );
};

proto.towns.JoinRoomRequest.prototype.clearRoomId = function () {
  jspb.Message.setOneofField(
    this,
    2,
    proto.towns.JoinRoomRequest.oneofGroups_[1],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.towns.JoinRoomRequest.prototype.hasRoomId = function () {
  return jspb.Message.getField(this, 2) != null;
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.towns.JoinRoomResponse = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    null,
    proto.towns.JoinRoomResponse.oneofGroups_
  );
};
goog.inherits(proto.towns.JoinRoomResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.towns.JoinRoomResponse.displayName = "proto.towns.JoinRoomResponse";
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.towns.JoinRoomResponse.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.towns.JoinRoomResponse.JoinStatusCheckerCase = {
  JOIN_STATUS_CHECKER_NOT_SET: 0,
  JOIN_STATUS: 1,
};

/**
 * @return {proto.towns.JoinRoomResponse.JoinStatusCheckerCase}
 */
proto.towns.JoinRoomResponse.prototype.getJoinStatusCheckerCase = function () {
  return /** @type {proto.towns.JoinRoomResponse.JoinStatusCheckerCase} */ (
    jspb.Message.computeOneofCase(
      this,
      proto.towns.JoinRoomResponse.oneofGroups_[0]
    )
  );
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.towns.JoinRoomResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.towns.JoinRoomResponse.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.towns.JoinRoomResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.towns.JoinRoomResponse.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        joinStatus: jspb.Message.getFieldWithDefault(msg, 1, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.towns.JoinRoomResponse}
 */
proto.towns.JoinRoomResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.towns.JoinRoomResponse();
  return proto.towns.JoinRoomResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.towns.JoinRoomResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.towns.JoinRoomResponse}
 */
proto.towns.JoinRoomResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {!proto.towns.JoinResponseStatus} */ (
          reader.readEnum()
        );
        msg.setJoinStatus(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.towns.JoinRoomResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.towns.JoinRoomResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.towns.JoinRoomResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.towns.JoinRoomResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = /** @type {!proto.towns.JoinResponseStatus} */ (
    jspb.Message.getField(message, 1)
  );
  if (f != null) {
    writer.writeEnum(1, f);
  }
};

/**
 * optional JoinResponseStatus join_status = 1;
 * @return {!proto.towns.JoinResponseStatus}
 */
proto.towns.JoinRoomResponse.prototype.getJoinStatus = function () {
  return /** @type {!proto.towns.JoinResponseStatus} */ (
    jspb.Message.getFieldWithDefault(this, 1, 0)
  );
};

/** @param {!proto.towns.JoinResponseStatus} value */
proto.towns.JoinRoomResponse.prototype.setJoinStatus = function (value) {
  jspb.Message.setOneofField(
    this,
    1,
    proto.towns.JoinRoomResponse.oneofGroups_[0],
    value
  );
};

proto.towns.JoinRoomResponse.prototype.clearJoinStatus = function () {
  jspb.Message.setOneofField(
    this,
    1,
    proto.towns.JoinRoomResponse.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.towns.JoinRoomResponse.prototype.hasJoinStatus = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * @enum {number}
 */
proto.towns.JoinResponseStatus = {
  SUCCESS: 0,
  ALREADY_FULL: 1,
  GAME_ENDED: 2,
  ROOM_NOT_FOUND: 3,
  ALREADY_CONNECTED: 4,
};

goog.object.extend(exports, proto.towns);
