/**
 * @fileoverview gRPC-Web generated client stub for towns
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: proto/room_joiner.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

const proto = {};
proto.towns = require("./room_joiner_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.RoomJoinerServiceClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.towns.RoomJoinerServicePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.towns.JoinRoomRequest,
 *   !proto.towns.JoinRoomResponse>}
 */
const methodDescriptor_RoomJoinerService_JoinRoom =
  new grpc.web.MethodDescriptor(
    "/towns.RoomJoinerService/JoinRoom",
    grpc.web.MethodType.UNARY,
    proto.towns.JoinRoomRequest,
    proto.towns.JoinRoomResponse,
    /**
     * @param {!proto.towns.JoinRoomRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.towns.JoinRoomResponse.deserializeBinary
  );

/**
 * @param {!proto.towns.JoinRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.towns.JoinRoomResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.towns.JoinRoomResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.towns.RoomJoinerServiceClient.prototype.joinRoom = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/towns.RoomJoinerService/JoinRoom",
    request,
    metadata || {},
    methodDescriptor_RoomJoinerService_JoinRoom,
    callback
  );
};

/**
 * @param {!proto.towns.JoinRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.towns.JoinRoomResponse>}
 *     Promise that resolves to the response
 */
proto.towns.RoomJoinerServicePromiseClient.prototype.joinRoom = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/towns.RoomJoinerService/JoinRoom",
    request,
    metadata || {},
    methodDescriptor_RoomJoinerService_JoinRoom
  );
};

module.exports = proto.towns;
